spring:
    application:
        name: eapw
    datasource:
        url: ${DATASOURCE_URL}
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    session:
        timeout: 24h
        jdbc:
            initialize-schema: always
    devtools:
        add-properties: false

server:
    servlet:
        session:
            timeout: 24h
            tracking-modes: cookie
            cookie:
                http-only: true
                secure: false
                name: JSESSIONID
                domain: localhost
                path: /
                max-age: 600
                same-site: strict